// fonts/<Family>/<files> 스캔 → public/shared/fonts.css(@font-face) 생성 + 바이너리 복사.
// 규칙: 폴더명 = font-family, 파일명 = weight/style.
// dev/prod 모두 prebuild(predev/prebuild)에서 실행.

import { readdir, mkdir, copyFile, writeFile, rm } from "node:fs/promises";
import { join, extname } from "node:path";

const SRC = "fonts";
const OUT_DIR = "public/shared/fonts";
const CSS_PATH = "public/shared/fonts.css";

const EXT_FORMAT = {
  ".woff2": "woff2",
  ".woff": "woff",
  ".ttf": "truetype",
  ".otf": "opentype",
};

const WEIGHT_MAP = {
  thin: 100,
  extralight: 200,
  ultralight: 200,
  light: 300,
  regular: 400,
  normal: 400,
  book: 400,
  medium: 500,
  semibold: 600,
  demibold: 600,
  bold: 700,
  extrabold: 800,
  ultrabold: 800,
  black: 900,
  heavy: 900,
};

// 파일명에서 weight 추출. 패밀리 접두를 떼고 "세그먼트(단어) 단위"로 매칭해
// 패밀리명에 weight 단어가 섞여 있어도(예: 'Light Sans') 오탐하지 않게 한다.
function weightFromName(base, family) {
  let s = base.toLowerCase();
  const fam = family.toLowerCase();
  if (s.startsWith(fam)) s = s.slice(fam.length);
  const segs = s.split(/[^a-z0-9]+/i).filter(Boolean);
  for (const seg of segs) {
    const word = seg.replace(/^[0-9]+/, ""); // 'Paperlogy-9Black' → '9black' → 'black'
    if (word in WEIGHT_MAP) return WEIGHT_MAP[word];
    if (/^[1-9]00$/.test(seg)) return Number(seg); // 'Inter-400'
  }
  return 400;
}

function isItalic(base) {
  return /italic|oblique/i.test(base);
}

async function listFontFamilies() {
  let dirs;
  try {
    dirs = await readdir(SRC, { withFileTypes: true });
  } catch {
    return [];
  }
  const families = [];
  for (const d of dirs) {
    if (!d.isDirectory() || d.name.startsWith(".")) continue;
    const files = (await readdir(join(SRC, d.name))).filter((f) =>
      Object.keys(EXT_FORMAT).includes(extname(f).toLowerCase()),
    );
    if (files.length) families.push({ family: d.name, files });
  }
  return families;
}

function faceRule(family, file) {
  const ext = extname(file).toLowerCase();
  const format = EXT_FORMAT[ext];
  const base = file.slice(0, -ext.length);
  const weight = weightFromName(base, family);
  const style = isItalic(base) ? "italic" : "normal";
  const url = `/shared/fonts/${encodeURIComponent(family)}/${encodeURIComponent(file)}`;
  return (
    `@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  src: url('${url}') format('${format}');\n` +
    `  font-weight: ${weight};\n` +
    `  font-style: ${style};\n` +
    `  font-display: swap;\n` +
    `}\n`
  );
}

async function main() {
  const families = await listFontFamilies();
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  let css = `/* AUTO-GENERATED by scripts/gen-fonts.mjs — 직접 수정 금지 */\n\n`;
  let faceCount = 0;
  const summary = [];

  for (const { family, files } of families) {
    await mkdir(join(OUT_DIR, family), { recursive: true });
    for (const file of files.sort()) {
      await copyFile(join(SRC, family, file), join(OUT_DIR, family, file));
      css += faceRule(family, file);
      faceCount++;
    }
    summary.push(`${family}(${files.length})`);
  }

  await writeFile(CSS_PATH, css, "utf8");
  console.log(
    `[gen-fonts] ${faceCount} @font-face from ${families.length} families: ${summary.join(", ")}`,
  );
}

await main();
