// design-guide/design-<name>.md → public/shared/themes/<name>.css
// 가이드 형식이 둘로 나뉨:
//   (a) 실제 :root { --token: #hex } 블록 (inventoy)
//   (b) 프로즈의 {colors.NAME} ... #hex 표기 (white-navy / supabase / lime-green)
// 둘 다 파싱해 원본 토큰을 뽑고, 템플릿이 쓰는 표준 토큰으로 정규화한다.

import { readdir, readFile, mkdir, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";

const SRC = "design-guide";
const OUT = "public/shared/themes";

// 가이드별: 폰트 + (가이드 원본 토큰키 → 표준 토큰) 매핑
const THEMES = {
  "white-navy": {
    font: "'Pretendard', system-ui, sans-serif",
    canon: { bg: "canvas", surface: "canvas-soft-3", ink: "ink", "ink-mute": "ink-mute", accent: "accent", "on-accent": "on-accent" },
  },
  "minimal-navy": {
    font: "'Pretendard', system-ui, sans-serif",
    canon: { bg: "canvas", surface: "surface", ink: "ink", "ink-mute": "ink-mute", accent: "navy", "on-accent": "on-navy" },
  },
  supabase: {
    font: "'Inter', 'Pretendard', system-ui, sans-serif",
    canon: { bg: "canvas", surface: "canvas-soft", ink: "ink", "ink-mute": "ink-mute", accent: "primary", "on-accent": "on-primary" },
  },
  "lime-green": {
    font: "'Paperlogy', 'Pretendard', system-ui, sans-serif",
    canon: { bg: "cream", surface: "cream-soft", ink: "ink", "ink-mute": "ink-mute", accent: "primary-bright", "on-accent": "on-lime" },
  },
  inventoy: {
    font: "'Paperlogy', 'Pretendard', system-ui, sans-serif",
    canon: { bg: "color-sub1", surface: "color-sub2", ink: "color-last", accent: "color-main", "on-accent": "color-last" },
  },
  ferrari: {
    font: "'Inter', 'Pretendard', system-ui, sans-serif",
    canon: { bg: "canvas", surface: "canvas-elevated", ink: "ink", "ink-mute": "muted", accent: "primary", "on-accent": "on-primary" },
  },
};

// 알 수 없는 가이드용 폴백
const CANON_FALLBACK = {
  bg: "#ffffff",
  surface: "#f5f5f5",
  ink: "#18181b",
  "ink-mute": "#6b7280",
  accent: "#2563eb",
  "on-accent": "#ffffff",
};

// 색 값: #hex 또는 rgba()/rgb(). hairline·glass 처럼 반투명이라 hex 로 못 적는 토큰이
// 있어서 rgba 도 받는다(hex 만 받으면 그런 토큰이 조용히 누락된다 — 변수는 없는데
// var(--hairline) 은 에러 없이 그냥 선이 사라지므로 눈치채기 어렵다).
const COLOR_VALUE = String.raw`#[0-9a-fA-F]{3,8}\b|rgba?\([^)\n]*\)`;

function extractTokens(md) {
  const tokens = {};
  // (a) --name: <color>
  for (const m of md.matchAll(new RegExp(String.raw`--([a-z0-9-]+)\s*:\s*(${COLOR_VALUE})`, "g"))) {
    if (!(m[1] in tokens)) tokens[m[1]] = m[2];
  }
  // (b) {colors.name} ... <color> (같은 줄, 단 다른 {colors.x} 토큰을 건너뛰지 않도록 gap 에서 '{' 제외)
  for (const m of md.matchAll(new RegExp(String.raw`\{colors\.([a-z0-9-]+)\}[^#\n{]*?(${COLOR_VALUE})`, "g"))) {
    if (!(m[1] in tokens)) tokens[m[1]] = m[2];
  }
  return tokens;
}

function buildCss(name, md) {
  const cfg = THEMES[name];
  const tokens = extractTokens(md);

  let css = `/* AUTO-GENERATED by scripts/gen-themes.mjs — design-guide/design-${name}.md 기반 */\n:root {\n`;

  const rawNames = Object.keys(tokens).sort();
  if (rawNames.length) {
    css += `  /* 가이드 원본 토큰 */\n`;
    for (const k of rawNames) css += `  --${k}: ${tokens[k]};\n`;
  }

  css += `\n  /* 템플릿 표준 토큰 (테마 교체 시 자동 반영) */\n`;
  const canon = cfg?.canon ?? {};
  for (const [cname, fb] of Object.entries(CANON_FALLBACK)) {
    const srcKey = canon[cname];
    let val = fb;
    if (srcKey && tokens[srcKey]) {
      val = tokens[srcKey];
    } else if (srcKey) {
      // canon 에 선언했는데 가이드에서 토큰을 못 찾음 → 조용한 폴백 대신 경고
      console.warn(`[gen-themes] ${name}: 표준토큰 '--${cname}' 소스 '${srcKey}' 미발견 → 폴백 ${fb}`);
    }
    css += `  --${cname}: ${val};\n`;
  }

  const font = cfg?.font ?? "'Pretendard', system-ui, sans-serif";
  css += `  --font-display: ${font};\n  --font-body: ${font};\n`;
  css += `}\n`;
  return css;
}

async function main() {
  let files;
  try {
    files = await readdir(SRC);
  } catch {
    files = [];
  }
  const names = files
    .filter((f) => /^design-.+\.md$/.test(f))
    .map((f) => f.replace(/^design-/, "").replace(/\.md$/, ""));

  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  for (const name of names) {
    const md = await readFile(join(SRC, `design-${name}.md`), "utf8");
    await writeFile(join(OUT, `${name}.css`), buildCss(name, md), "utf8");
  }
  console.log(`[gen-themes] ${names.length} themes: ${names.join(", ")}`);
}

await main();
